### ----------------- DEV ------------------ ###

### GET default/index
GET http://localhost:3000
### GET 404
GET http://localhost:3000/404
### GET API swagger docs
GET http://localhost:3000/api-docs
### GET all characters
GET http://localhost:3000/characters
### GET 1 character
GET http://localhost:3000/characters/63def425bb166f3e221a6ef3
### POST - create character
POST http://localhost:3000/characters HTTP/1.1
content-type: application/json

{
  "charName": "mori",
  "level": 1,
  "money": 1000,
  "createdAt": "02/02/2023",
  "lastPlayed": "02/03/2023",
  "owner": "tylertucker55",
  "location": "1, 1, 1"
}
### PUT - update contact
PUT http://localhost:3000/characters/63d853e32ce97a2ac274bbd9 HTTP/1.1
content-type: application/json

{
  "charName": "mori2",
  "level": 1,
  "money": 1000,
  "createdAt": "02/02/2023",
  "lastPlayed": "02/03/2023",
  "owner": "tylertucker55",
  "location": "1, 1, 1"
}
### DELETE character
DELETE http://localhost:3000/characters/63d855468ac64a480e3550cd HTTP/1.1

### GET all items
GET http://localhost:3000/items

### ----------------- PROD ------------------ ###

### GET default/index
GET https://cse341-psei.onrender.com/
### GET 404
GET http://cse341-psei.onrender.com/404
### GET API swagger docs
GET http://cse341-psei.onrender.com/api-docs
### GET all characters
GET https://cse341-psei.onrender.com/characters
### GET 1 contact
GET https://cse341-psei.onrender.com/characters/63c0723ecba10a8bdcd6290f
### POST - create contact
POST http://cse341-psei.onrender.com/characters HTTP/1.1
content-type: application/json

{
  "charName": "mori",
  "level": 1,
  "money": 1000,
  "createdAt": "02/02/2023",
  "lastPlayed": "02/03/2023",
  "owner": "tylertucker55",
  "location": "1, 1, 1"
}
### PUT - update contact
PUT http://cse341-psei.onrender.com/characters/63c0723ecba10a8bdcd6290f HTTP/1.1
content-type: application/json

{
  "charName": "mori2",
  "level": 1,
  "money": 1000,
  "createdAt": "02/02/2023",
  "lastPlayed": "02/03/2023",
  "owner": "tylertucker55",
  "location": "1, 1, 1"
}
### DELETE contact
DELETE http://cse341-psei.onrender.com/characters/63c0723ecba10a8bdcd6290f HTTP/1.1