### ----------------- DEV ------------------ ###

### GET default/index
GET http://localhost:3000
### GET 404
GET http://localhost:3000/404
### GET API swagger docs
GET http://localhost:3000/api-docs

### --------- Login ----------

### Get auth token
POST http://localhost:3000/login HTTP/1.1
Content-Type: application/json

{
  "email": "tyler@turner.com",
  "password": "elephant"
}

### --------- Characters ----------

### GET all chars with auth
GET http://localhost:3000/characters
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2ZhOTdiYzg2MjRhM2E0YjU0OGE2ZjIiLCJmaXJzdE5hbWUiOiJ0eWxlciIsImxhc3ROYW1lIjoidHVybmVyIiwiZW1haWwiOiJ0eWxlckB0dXJuZXIuY29tIiwicGFzc3dvcmQiOiJlbGVwaGFudCIsImlhdCI6MTY3Nzk3MTMyMX0.IZWLvSF-M9Masn4hSADAYE4TISZfWEYNwwzYpPQenTU

### GET all chars with (BAD) auth
GET http://localhost:3000/characters
Authorization: Bearer 123

### GET 1 character
GET http://localhost:3000/characters/63def425bb166f3e221a6ef3
### POST - create character (bad schema)
POST http://localhost:3000/characters HTTP/1.1
content-type: application/json

{
  "charName": "adasda",
  "level": 71,
  "money": 10000,
  "createdAt": "02/02/2023",
  "lastPlayed": "02/03/2023",
  "owner": "webcooltz",
  "location": "1, 1, 1"
}
### POST - create character (good schema)
POST http://localhost:3000/characters HTTP/1.1
content-type: application/json

{
  "charName": "mori",
  "level": 1,
  "money": 1000,
  "createdAt": "02/02/2023",
  "lastPlayed": "02/03/2023",
  "owner": "webcooltz",
  "location": "1, 1, 1"
}
### PUT - update character
PUT http://localhost:3000/characters/63faa4c937b5287f6aa81a37 HTTP/1.1
content-type: application/json

{
  "charName": "mori2",
  "level": 1,
  "money": 1000,
  "createdAt": "02/02/2023",
  "lastPlayed": "02/03/2023",
  "owner": "tylertucker55",
  "location": "1, 1, 1"
}
### DELETE character
DELETE http://localhost:3000/characters/63df5144357029cb10c14e27 HTTP/1.1

### --------- Users ----------

### GET all users with auth
GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InR5bGVyQHR1cm5lci5jb20iLCJwYXNzd29yZCI6ImVsZXBoYW50IiwiaWF0IjoxNjc3NzkwMTk5fQ.GNTKY38qfv2MakOBso5Cc4ySg_H-UMp7d2dPxDmVYIM

### GET all users with (BAD) auth
GET http://localhost:3000/users
Authorization: Bearer 123

### GET 1 user
GET http://localhost:3000/users/63fa97bc8624a3a4b548a6f2
### POST - create user (bad password)
POST http://localhost:3000/users HTTP/1.1
content-type: application/json

{
  "firstName": "tdog",
  "lastName": "turner",
  "email": "tdog@dog.com",
  "password": "dog"
}
### POST - create user (bad schema)
POST http://localhost:3000/users HTTP/1.1
content-type: application/json

{
  "firstName": "t",
  "lastName": "turner",
  "email": "tdog@dog.com",
  "password": "Hell0world!"
}
### POST - create user (good password/schema)
POST http://localhost:3000/users HTTP/1.1
content-type: application/json

{
  "firstName": "tdog",
  "lastName": "turner",
  "email": "tdog@dog.com",
  "password": "Hell0world!"
}
### PUT - update user (bad password)
PUT http://localhost:3000/users/63faa1eedde84efcb205426b HTTP/1.1
content-type: application/json

{
  "firstName": "kdog",
  "lastName": "lamar",
  "email": "kdog@dog.com",
  "password": "dog1"
}
### PUT - update user (good password)
PUT http://localhost:3000/users/63faa1eedde84efcb205426b HTTP/1.1
content-type: application/json

{
  "firstName": "kdog",
  "lastName": "lamar",
  "email": "kdog@dog.com",
  "password": "Hell0world!"
}
### DELETE user
DELETE http://localhost:3000/users/63fab0337a6e1fd5a4d8d983 HTTP/1.1


### --------#--------- PROD -----------#------- ###

### GET default/index
GET https://rpg-pvd4.onrender.com
### GET 404
GET https://rpg-pvd4.onrender.com/404
### GET API swagger docs
GET https://rpg-pvd4.onrender.com/api-docs

### --------- Characters ----------

### GET all characters
GET https://rpg-pvd4.onrender.com/characters
### GET 1 character
GET https://rpg-pvd4.onrender.com/characters/63def425bb166f3e221a6ef3
### POST - create character (bad schema)
POST https://rpg-pvd4.onrender.com/characters HTTP/1.1
content-type: application/json

{
  "charName": "adasda",
  "level": 71,
  "money": 10000,
  "createdAt": "02/02/2023",
  "lastPlayed": "02/03/2023",
  "owner": "webcooltz",
  "location": "1, 1, 1"
}
### POST - create character (good schema)
POST https://rpg-pvd4.onrender.com/characters HTTP/1.1
content-type: application/json

{
  "charName": "mori",
  "level": 1,
  "money": 1000,
  "createdAt": "02/02/2023",
  "lastPlayed": "02/03/2023",
  "owner": "webcooltz",
  "location": "1, 1, 1"
}
### PUT - update character
PUT https://rpg-pvd4.onrender.com/characters/63faa4c937b5287f6aa81a37 HTTP/1.1
content-type: application/json

{
  "charName": "mori2",
  "level": 1,
  "money": 1000,
  "createdAt": "02/02/2023",
  "lastPlayed": "02/03/2023",
  "owner": "tylertucker55",
  "location": "1, 1, 1"
}
### DELETE character
DELETE https://rpg-pvd4.onrender.com/characters/63d855468ac64a480e3550cd HTTP/1.1

### --------- Users ----------

### GET all users
GET https://rpg-pvd4.onrender.com/users
### GET 1 user
GET https://rpg-pvd4.onrender.com/users/63fa97bc8624a3a4b548a6f2
### POST - create user (bad password)
POST https://rpg-pvd4.onrender.com/users HTTP/1.1
content-type: application/json

{
  "firstName": "tdog",
  "lastName": "turner",
  "email": "tdog@dog.com",
  "password": "dog"
}
### POST - create user (bad schema)
POST https://rpg-pvd4.onrender.com/users HTTP/1.1
content-type: application/json

{
  "firstName": "t",
  "lastName": "turner",
  "email": "tdog@dog.com",
  "password": "Hell0world!"
}
### POST - create user (good password/schema)
POST https://rpg-pvd4.onrender.com/users HTTP/1.1
content-type: application/json

{
  "firstName": "tdog",
  "lastName": "turner",
  "email": "tdog@dog.com",
  "password": "Hell0world!"
}
### PUT - update user (bad password)
PUT https://rpg-pvd4.onrender.com/users/63faa1eedde84efcb205426b HTTP/1.1
content-type: application/json

{
  "firstName": "kdog",
  "lastName": "lamar",
  "email": "kdog@dog.com",
  "password": "dog1"
}
### PUT - update user (good password)
PUT https://rpg-pvd4.onrender.com/users/63faa1eedde84efcb205426b HTTP/1.1
content-type: application/json

{
  "firstName": "kdog",
  "lastName": "lamar",
  "email": "kdog@dog.com",
  "password": "Hell0world!"
}
### DELETE user
DELETE https://rpg-pvd4.onrender.com/users/63fab0337a6e1fd5a4d8d983 HTTP/1.1
